### ISSUE TITLE
Placa solar

### ISSUE THREAD

**Issue by LucasQuinino** [buff-buff-studio/SolarBuff#35]

**Comment by Jubabibou** [comment]
![Image](https://github.com/buff-buff-studio/SolarBuff/assets/69398641/4b72b734-668e-41fb-b5d3-f0798ba5bc35)




![Image](https://github.com/buff-buff-studio/SolarBuff/assets/69398641/7f3fa28b-2c94-4073-9ba4-f5b482304689)
