### ISSUE TITLE
2 variações de cerca high tech (meio, quina)

### ISSUE THREAD

**Issue by LucasQuinino** [buff-buff-studio/SolarBuff#38]

**Comment by Bozzipontojpg** [comment]
![Image](https://github.com/buff-buff-studio/SolarBuff/assets/72225642/04cc0738-051b-426b-9e1f-e27d5bd91e3f)

Da direita pra esquerda: Canto e meio
Precisa mexer nas proporções pra deixar mais estilizado, mas por enquanto deixei assim, dá pra mexer dps q texturizar. @LucasQuinino opine no design se parece muito um stickman com chapéu de chef ou se tá bão.

**Comment by Bozzipontojpg** [comment]
Atualizadas, agora tão mais grossas.
